---- ---- ---- ---- ---- ---- ---- ---- ---- ----
-- v1.1 2020.03.14 정민호
--  * '도로명주소_건물_도로명_코드' 테이블 pk 변경으로 인한 테이블 생성쿼리 수정
--   - 주소_시군구_주소코드 + 주소_읍면동_일련번호 -> 주소_시군구_주소코드 + 주소_도로_일련번호 + 주소_읍면동_일련번호
--  * 데이터 import 시 원할하게 입력하기 위해 원본 데이터 순서대로 컬럼 순서 변경

-- v1.3 2020.05.07 정민호
--  * '공동주택_목록_법정동 테이블(TBL_APT_LIS_LGD)' 테이블에 컬럼 추가
--   - 주소_법정동_주소코드(ADR_LGD_ACD) - VARCHAR(14)
---- ---- ---- ---- ---- ---- ---- ---- ---- ----


CREATE TABLE ROWDATA_ADDR.TBL_APT_DTL( -- 공동주택_상세 테이블
	APT_HCD VARCHAR(9) NOT NULL ,  -- 공동주택_단지코드 - 단지코드_VAR9
	APT_HSC_NM VARCHAR(200) NOT NULL ,  -- 공동주택_단지_명칭 - 명칭_VAR200
	APT_LGD_ADR_CNT VARCHAR(1000) NOT NULL ,  -- 공동주택_법정동_주소_내용 - 내용_VAR1000
	APT_LTO_FRM_NM VARCHAR(200) NOT NULL ,  -- 공동주택_분양_형태_명칭 - 명칭_VAR200
	APT_HET_MTH_NM VARCHAR(200) NOT NULL ,  -- 공동주택_난방_방식_명칭 - 명칭_VAR200
	APT_ALL_ARA NUMERIC(20,5) NOT NULL ,  -- 공동주택_전체_면적 - 면적_NMR20-5
	APT_DNG_NMR NUMERIC NOT NULL ,  -- 공동주택_동_개수 - 개수_INT
	APT_HSH_NMR NUMERIC NOT NULL ,  -- 공동주택_세대_개수 - 개수_INT
	APT_BLR_NM VARCHAR(200) NOT NULL ,  -- 공동주택_시공사_명칭 - 명칭_VAR200
	APT_DVL_NM VARCHAR(200) NOT NULL ,  -- 공동주택_시행사_명칭 - 명칭_VAR200
	APT_MNO_CNP VARCHAR(20) NOT NULL ,  -- 공동주택_관리사무소_연락처 - 연락처_VAR20
	APT_MNO_FAX_CNP VARCHAR(20) NOT NULL ,  -- 공동주택_관리사무소_팩스_연락처 - 연락처_VAR20
	APT_HMP_ADR_CNT VARCHAR(1000)  ,  -- 공동주택_홈페이지_주소_내용 - 내용_VAR1000
	APT_HSC_CLF_NM VARCHAR(200) NOT NULL ,  -- 공동주택_단지_분류_명칭 - 명칭_VAR200
	APT_RDN_ADR_CNT VARCHAR(1000)  ,  -- 공동주택_도로명_주소_내용 - 내용_VAR1000
	APT_LAK_NMR NUMERIC NOT NULL ,  -- 공동주택_호수_개수 - 개수_INT
	APT_MNM_NM VARCHAR(200) NOT NULL ,  -- 공동주택_관리방식_명칭 - 명칭_VAR200
	APT_CDT_NM VARCHAR(200) NOT NULL ,  -- 공동주택_복도유형_명칭 - 명칭_VAR200
	APT_USE_CNS_OGD VARCHAR(8) NOT NULL ,  -- 공동주택_사용_승인_원본일자 - 원본일자_VAR8
	APT_MNC_LVY_ARA NUMERIC(20,5) NOT NULL ,  -- 공동주택_관리비_부과_면적 - 면적_NMR20-5
	APT_0_60_HSH_NMR NUMERIC NOT NULL ,  -- 공동주택_0_60_세대_개수 - 개수_INT
	APT_60_85_HSH_NMR NUMERIC NOT NULL ,  -- 공동주택_60_85_세대_개수 - 개수_INT
	APT_85_135_HSH_NMR NUMERIC NOT NULL ,  -- 공동주택_85_135_세대_개수 - 개수_INT
	APT_135_999_HSH_NMR NUMERIC NOT NULL ,  -- 공동주택_135_999_세대_개수 - 개수_INT
	APT_HSC_PUA_SMT_ARA NUMERIC(20,5) NOT NULL ,  -- 공동주택_단지_전용면적_합계_면적 - 면적_NMR20-5
	ADR_LGD_ACD VARCHAR(14) NOT NULL ,  -- 주소_법정동_주소코드 - 주소코드_VAR14

	CONSTRAINT TBL_APT_DTL_pkey PRIMARY KEY (APT_HCD)
);


CREATE TABLE ROWDATA_ADDR.TBL_APT_LIS_LGD( -- 공동주택_목록_법정동 테이블
	APT_HCD VARCHAR(9) NOT NULL ,  -- 공동주택_단지코드 - 단지코드_VAR9
	APT_HSC_NM VARCHAR(200) NOT NULL ,  -- 공동주택_단지_명칭 - 명칭_VAR200
	ADR_LGD_ACD VARCHAR(14) NOT NULL ,  -- 주소_법정동_주소코드 - 주소코드_VAR14

	CONSTRAINT TBL_APT_LIS_LGD_pkey PRIMARY KEY (APT_HCD)
);


CREATE TABLE ROWDATA_ADDR.TBL_APT_LIS_ADD( -- 공동주택_목록_행정동 테이블
	APT_HCD VARCHAR(9) NOT NULL ,  -- 공동주택_단지코드 - 단지코드_VAR9
	APT_HSC_NM VARCHAR(200) NOT NULL ,  -- 공동주택_단지_명칭 - 명칭_VAR200

	CONSTRAINT TBL_APT_LIS_ADD_pkey PRIMARY KEY (APT_HCD)
);






COMMENT ON TABLE ROWDATA_ADDR.TBL_APT_DTL IS '공동주택_상세';
COMMENT ON COLUMN ROWDATA_ADDR.TBL_APT_DTL.APT_HCD IS '공동주택_단지코드';
COMMENT ON COLUMN ROWDATA_ADDR.TBL_APT_DTL.APT_HSC_NM IS '공동주택_단지_명칭';
COMMENT ON COLUMN ROWDATA_ADDR.TBL_APT_DTL.APT_LGD_ADR_CNT IS '공동주택_법정동_주소_내용';
COMMENT ON COLUMN ROWDATA_ADDR.TBL_APT_DTL.APT_LTO_FRM_NM IS '공동주택_분양_형태_명칭';
COMMENT ON COLUMN ROWDATA_ADDR.TBL_APT_DTL.APT_HET_MTH_NM IS '공동주택_난방_방식_명칭';
COMMENT ON COLUMN ROWDATA_ADDR.TBL_APT_DTL.APT_ALL_ARA IS '공동주택_전체_면적';
COMMENT ON COLUMN ROWDATA_ADDR.TBL_APT_DTL.APT_DNG_NMR IS '공동주택_동_개수';
COMMENT ON COLUMN ROWDATA_ADDR.TBL_APT_DTL.APT_HSH_NMR IS '공동주택_세대_개수';
COMMENT ON COLUMN ROWDATA_ADDR.TBL_APT_DTL.APT_BLR_NM IS '공동주택_시공사_명칭';
COMMENT ON COLUMN ROWDATA_ADDR.TBL_APT_DTL.APT_DVL_NM IS '공동주택_시행사_명칭';
COMMENT ON COLUMN ROWDATA_ADDR.TBL_APT_DTL.APT_MNO_CNP IS '공동주택_관리사무소_연락처';
COMMENT ON COLUMN ROWDATA_ADDR.TBL_APT_DTL.APT_MNO_FAX_CNP IS '공동주택_관리사무소_팩스_연락처';
COMMENT ON COLUMN ROWDATA_ADDR.TBL_APT_DTL.APT_HMP_ADR_CNT IS '공동주택_홈페이지_주소_내용';
COMMENT ON COLUMN ROWDATA_ADDR.TBL_APT_DTL.APT_HSC_CLF_NM IS '공동주택_단지_분류_명칭';
COMMENT ON COLUMN ROWDATA_ADDR.TBL_APT_DTL.APT_RDN_ADR_CNT IS '공동주택_도로명_주소_내용';
COMMENT ON COLUMN ROWDATA_ADDR.TBL_APT_DTL.APT_LAK_NMR IS '공동주택_호수_개수';
COMMENT ON COLUMN ROWDATA_ADDR.TBL_APT_DTL.APT_MNM_NM IS '공동주택_관리방식_명칭';
COMMENT ON COLUMN ROWDATA_ADDR.TBL_APT_DTL.APT_CDT_NM IS '공동주택_복도유형_명칭';
COMMENT ON COLUMN ROWDATA_ADDR.TBL_APT_DTL.APT_USE_CNS_OGD IS '공동주택_사용_승인_원본일자';
COMMENT ON COLUMN ROWDATA_ADDR.TBL_APT_DTL.APT_MNC_LVY_ARA IS '공동주택_관리비_부과_면적';
COMMENT ON COLUMN ROWDATA_ADDR.TBL_APT_DTL.APT_0_60_HSH_NMR IS '공동주택_0_60_세대_개수';
COMMENT ON COLUMN ROWDATA_ADDR.TBL_APT_DTL.APT_60_85_HSH_NMR IS '공동주택_60_85_세대_개수';
COMMENT ON COLUMN ROWDATA_ADDR.TBL_APT_DTL.APT_85_135_HSH_NMR IS '공동주택_85_135_세대_개수';
COMMENT ON COLUMN ROWDATA_ADDR.TBL_APT_DTL.APT_135_999_HSH_NMR IS '공동주택_135_999_세대_개수';
COMMENT ON COLUMN ROWDATA_ADDR.TBL_APT_DTL.APT_HSC_PUA_SMT_ARA IS '공동주택_단지_전용면적_합계_면적';
COMMENT ON COLUMN ROWDATA_ADDR.TBL_APT_DTL.ADR_LGD_ACD IS '주소_법정동_주소코드';



COMMENT ON TABLE ROWDATA_ADDR.TBL_APT_LIS_LGD IS '공동주택_목록_법정동';
COMMENT ON COLUMN ROWDATA_ADDR.TBL_APT_LIS_LGD.APT_HCD IS '공동주택_단지코드';
COMMENT ON COLUMN ROWDATA_ADDR.TBL_APT_LIS_LGD.APT_HSC_NM IS '공동주택_단지_명칭';



COMMENT ON TABLE ROWDATA_ADDR.TBL_APT_LIS_ADD IS '공동주택_목록_행정동';
